CREATE TABLE USERS(
	UserID SERIAL PRIMARY KEY,
	UserName TEXT,
	PhoneNo TEXT,
	Email TEXT,
	Password TEXT
)


CREATE TABLE ROUTE(
	RouteID SERIAL PRIMARY KEY,
	StartLocation TEXT NOT NULL,
	EndLocation TEXT NOT NULL,
	Distance FLOAT
)


CREATE TABLE BUS(
	BusID SERIAL PRIMARY KEY,
	BusNumber INTEGER,
	Capacity INTEGER,
	RouteID INTEGER REFERENCES ROUTE(RouteID)
)

CREATE TABLE SCHEDULE(
	ScheduleID SERIAL PRIMARY KEY,
	DepatureTime TIMESTAMP NOT NULL,
	ArrivalTime TIMESTAMP,
	BusID INTEGER REFERENCES BUS(BusID)
)

CREATE TABLE BOOKING (
    BookingID SERIAL PRIMARY KEY,
    DateTime TIMESTAMP NOT NULL,
    Status VARCHAR(20) CHECK (Status IN ('Confirmed', 'Cancelled')),
    UserID INT REFERENCES USERS(UserID),
    ScheduleID INT REFERENCES SCHEDULE(ScheduleID)
);

CREATE TABLE PAYMENT (
    PaymentID SERIAL PRIMARY KEY,
    Amount FLOAT NOT NULL,
    PaymentDate DATE NOT NULL,
    Status VARCHAR(20) CHECK (Status IN ('Paid', 'Pending')),
    BookingID INT REFERENCES BOOKING(BookingID)
);